#!/usr/bin/env bash
# Deploy the CDK stack to LocalStack using native CDK with endpoint override.
# Produces .env.localstack with resource URLs/names for the app to consume.
#
# Security: Only dummy credentials are used here — they are never persisted
# to disk. LocalStack does not validate credentials; these are required only
# to satisfy the AWS SDK credential chain. Real AWS credentials should NEVER
# be set in this script or in .env.localstack.
set -euo pipefail

GREEN='\033[0;32m'
RED='\033[0;31m'
DIM='\033[2m'
NC='\033[0m'

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CDK_DIR="$REPO_ROOT/infra/cdk"
OUTPUTS_FILE="/tmp/cdk-localstack-outputs.json"
ENV_FILE="$REPO_ROOT/.env.localstack"
STACK_NAME="fsa-local-local"

# ── LocalStack endpoint overrides (native AWS SDK v3 support) ──
# These env vars redirect ALL AWS SDK calls to LocalStack.
# AWS_ENDPOINT_URL is the standard override supported by AWS SDK v3 and CDK >= 2.177.
export AWS_ENDPOINT_URL=http://localhost.localstack.cloud:4566
export AWS_ENDPOINT_URL_S3=http://s3.localhost.localstack.cloud:4566

# ── Dummy credentials (never persisted, not validated by LocalStack) ──
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_DEFAULT_REGION=us-east-1
export CDK_DEFAULT_ACCOUNT=000000000000
export CDK_DEFAULT_REGION=us-east-1

# 1. Health check — LocalStack must be running
if ! curl -sf http://localhost:4566/_localstack/health > /dev/null 2>&1; then
  printf "  ${RED}LocalStack is not running.${NC} Start it with: docker compose up -d\n"
  exit 1
fi

# 2. Bootstrap (idempotent — creates CDK staging bucket in LocalStack)
printf "  ${DIM}CDK bootstrap (LocalStack)...${NC}"
cd "$CDK_DIR"
npx cdk bootstrap aws://000000000000/us-east-1 \
  -c env=local -c owner=local \
  --quiet 2>&1 | sed 's/^/    /'
printf "\r  ${GREEN}CDK bootstrap done${NC}             \n"

# 3. Deploy with skipCognito (LocalStack Community lacks Cognito support)
printf "  ${DIM}CDK deploy (LocalStack)...${NC}"
npx cdk deploy "$STACK_NAME" \
  -c env=local -c owner=local -c skipCognito=true \
  --outputs-file "$OUTPUTS_FILE" \
  --require-approval never 2>&1 | sed 's/^/    /'
printf "\r  ${GREEN}CDK deploy done${NC}                \n"

# 4. Parse outputs → .env.localstack (contains only resource names/URLs, no secrets)
if [ ! -f "$OUTPUTS_FILE" ]; then
  printf "  ${RED}CDK outputs file not found at $OUTPUTS_FILE${NC}\n"
  exit 1
fi

S3_BUCKET=$(jq -r ".[\"$STACK_NAME\"].S3BucketName" "$OUTPUTS_FILE")
SQS_MESSAGE_QUEUE_URL=$(jq -r ".[\"$STACK_NAME\"].MessageQueueUrl" "$OUTPUTS_FILE")

cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by scripts/localstack-deploy.sh — do not edit manually.
# Contains only resource identifiers (bucket names, queue URLs) and local endpoints.
# No credentials, tokens, or secrets are stored in this file.
S3_BUCKET=$S3_BUCKET
S3_ENDPOINT=http://localhost:4566
SQS_MESSAGE_QUEUE_URL=$SQS_MESSAGE_QUEUE_URL
SQS_ENDPOINT=http://localhost:4566
ENVEOF

printf "  ${GREEN}Wrote $ENV_FILE${NC}\n"
rm -f "$OUTPUTS_FILE"
